auth_login/urls.py
from django.urls import path, include
from auth_login import views
from django.contrib.auth import views as auth_views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    #path('profile/purchases/<int:id>', views.purchases, name='purchases'),
    path('profile/edit', views.editProfile, name='edit'),
    path('profile/change_password', views.change_password, name='change_password'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('auth/', include('auth_login.urls', namespace='auth')),
    #Me trae las funciones de reseteo de contraseña que provee Django
    path('accounts/', include('django.contrib.auth.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path, include
from orders import views
from orders.models import Product, Detail
from django.conf.urls import url
from .views import *
app_name = 'orders'

urlpatterns = [
    path('', views.home, name='home'),
    path('crear/', views.createOrder, name='create'),
    path('ordenes/', views.listOrder, name='list-orders'),
    path('editar-orden/<int:id>', views.updateOrder, name='update-order'),
    path('crear-detalle/<int:id>', views.createDetail, name='create-detail'),
    path('editar-detalle/<int:id>', views.updateDetail, name='update-detail'),
    path('detalles/<int:id>', views.listDetail, name='list-detail'),
    path('eliminar-detalle/<int:id>', views.deleteDetail, name='delete-detail'),
    path('export_csv/', views.export_csv, name='export-csv'),
    path('export_pdf/', views.render_to_pdf, name="export-pdf" ),
    path('checkout/<int:id>/', views.sendMail, name='send-email'),
    path('client-json/', get_json_client_data, name='client-json'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

GENDERS = (
    ('H', 'Hombre'),
    ('M', 'Mujer'),
    ('O', 'Otro'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, default='No indica')
    gender = models.CharField(max_length=1, choices=GENDERS, default='N')
    city = models.CharField(max_length=50, default='No indica')
    phone = models.IntegerField(default=0)
    
    def __str__(self):
        return self.user.first_name

# Función que se ejecuta cuando se crea un usuario nuevo, realiza un trigger que asocia ese usuario nuevo a un perfil UserProfile
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)

class Client(models.Model):
    name = models.CharField(max_length=50)
    codigo = models.IntegerField()
    def __str__(self):
        return self.name

class Sucursal(models.Model):
    name = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    codigo_sucursal = models.IntegerField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE, default=1)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    codigo = models.IntegerField()
    def __str__(self):
        return self.name
        
class Sale(models.Model):
    date = models.DateField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    seller = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    total = models.PositiveIntegerField()

    def __str__(self):
        return str(self.id)

class Detail(models.Model):
    Numero_boleta = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    quantity = models.PositiveIntegerField()
    
    def __str__(self):
        return str(self.Numero_boleta)
        

orders/forms.py
from django import forms
from orders.models import Sale, Detail, Product, Client


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class DetailForm(forms.ModelForm):
    class Meta:
        model = Detail
        fields = ('__all__')
        exclude = ('Numero_boleta',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'product' in self.data:
            self.fields['product'].queryset = Product.objects.all()
        elif self.instance.pk:
            self.fields['product'].queryset = Product.objects.all().filter(id=self.instance.product.pk)


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'
        exclude = ('date', 'total', 'seller')

orders/views.py
import json
import csv
import datetime
import io as BytesIO
from django.core.exceptions import SuspiciousFileOperation
from django.core.files.base import ContentFile
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from orders.forms import ProductForm, SaleForm, DetailForm
from orders.models import Sale, UserProfile, Detail, Client, Sucursal, Product
from datetime import date
from django.template.loader import render_to_string, get_template
from django.db.models import Q
from django.core.mail import send_mail, EmailMultiAlternatives
from orders.utils import render_to_pdf


# Create your views here.


def home(request):
    template_name = 'home.html'
    data = {}
    return render(request, template_name, data)


def createOrder(request):
    data = {}
    template_name = 'create-orden.html'
    #Obtengo al usuario
    user = UserProfile.objects.get(user=request.user.id)
    form = SaleForm(request.POST or None, request.FILES or None)
    if request.is_ajax(): #Si la request viene de ajax
        term = request.GET.get('term') #Obtengo el termino, que es un input del usuario
        clients = Client.objects.all().filter(name__icontains=term) #Realizo una consulta en los productos buscando el input del usuario
        return JsonResponse(list(clients.values()), safe=False)

    if request.method == 'POST': #Si el metodo es POST
        #Llama al formulario SaleForm
        #form = SaleForm(request.POST or None, request.FILES or None)
        today = date.today() #Fecha de hoy
        if form.is_valid():
            cliente = form.cleaned_data['client'] #Extraigo los datos del formulario
            sucursal = form.cleaned_data['sucursal'] #Extraigo los datos del formulario
            sale = Sale.objects.create(
                date=today,
                client=cliente,
                sucursal=sucursal,
                seller=user,
                total=20,
            ) #Creo un objeto con los datos del formulario que será guardado en la base de datos
            sale.save() #Guardo el objeto
            return redirect('orders:create-detail', id=sale.id) #Redirigo al usuario a crear los detalles de la nota de venta
    else: #Si el metodo no es POST
        form = SaleForm(request.POST or None, request.FILES or None) #Solo llamo al formulario

    return render(request, template_name, {'form': form, })

def get_json_client_data(request):
    qs_val = list(Client.objects.values())
    return JsonResponse({'data':qs_val})

# AJAX
def load_cities(request):
    client_id = request.GET.get('client_id')
    template_name = 'sucursal-dropdown.html'
    sucursales = Sucursal.objects.filter(client_id=client_id)
    #return render(request, template_name, {'sucursales': sucursales})
    return JsonResponse(list(sucursales.values('id', 'name')), safe=False)


def listOrder(request):
    data = {}
    template_name = 'Orders.html'
    #Traigo todas las ordenes existentes, ordenadas por ID
    data['orders'] = Sale.objects.all().order_by('-id')

    if not data['orders']:
        pass
    else:
        pass

    return render(request, template_name, data)


def listDetail(request, id):
    data = {}
    template_name = 'list-detail.html'
    #Traigo los detalles de una nota de venta, manejados por el id enviado por parametro de la funcion
    data['details'] = Detail.objects.filter(Numero_boleta=id)
    if not data['details']:
        return redirect('orders:create-detail', id=id)
    else:
        data['client'] = data['details'][0].Numero_boleta.client #Cliente de la nota de venta
        data['sucursal'] = data['details'][0].Numero_boleta.sucursal #Sucursal de la nota de venta
    return render(request, template_name, data)


def updateOrder(request, id):
    template_name = 'update-order.html'
    data = {}
    #Obtengo la nota de venta mediante su ID
    order = Sale.objects.filter(pk=id)

    if request.method == 'POST':
        data['form'] = SaleForm(request.POST or None, instance=order) #Inicializo un formulario con los datos de la instancia order
        if data['form'].is_valid():
            order.save() #Si el formulario es valido, actualizo la orden
            return redirect('orders:list-orders')
    else:
        data['form'] = SaleForm(instance=order) #Inicializo un formulario con los datos de la instancia order

    return render(request, template_name, data)


    
def sendMail(request, id):
    data = {}
    template_name = 'checkout.html'
    data['sale'] = Sale.objects.get(pk=id)
    data['details'] = Detail.objects.filter(Numero_boleta=data['sale'].id) #Obtengo los detalles de la nota de venta
    #print(data['sales'])
    subject = 'Nota de venta'
    message = render_to_string('email1.html', data)
    text_content = 'xd'
    from_email = 'avisos@cbsystems.cl'
    html_content = '<h3>AAJJAJ</h3><p>{0}</p>'.format(text_content)
    """ send_mail(
        'Subject here'+str(data['sales'].id),
        'Here is the message.',
        'avisos@cbsystems.cl',
        ['cristobal.bustamante.q@gmail.com', 'xd@gmail.com'],
        fail_silently=False,
    ) #Envio mail """
    msg = EmailMultiAlternatives(
        subject,
        text_content,
        from_email,
        ['cristobal.bustamante.q@gmail.com']
    )
    pdf = render_to_pdf('email1.html', data)
    msg.attach('report.pdf', pdf)
    msg.attach_alternative(message, "text/html")
    msg.send()
    return render(request, template_name, data)

def createDetail(request, id):
    data = {}
    template_name = 'create-detail.html'
    data['sale'] = Sale.objects.get(pk=id) #Obtengo la nota de venta
    data['AIDI'] = data['sale'].id
    data['details'] = Detail.objects.filter(Numero_boleta=data['sale'].id) #Obtengo los detalles de la nota de venta

    if request.is_ajax(): #Si la request viene de ajax
        term = request.GET.get('term') #Obtengo el termino, que es un input del usuario
        products = Product.objects.all().filter(name__icontains=term) #Realizo una consulta en los productos buscando el input del usuario
        return JsonResponse(list(products.values()), safe=False)

    if request.method == 'POST':
        data['form'] = DetailForm(request.POST or None, request.FILES or None)
        if data['form'].is_valid():
            product = data['form'].cleaned_data['product'] #Extraigo los datos del formulario
            quantity = data['form'].cleaned_data['quantity'] #Extraigo los datos del formulario
            detail = Detail.objects.create(
                Numero_boleta=data['sale'],
                product=product,
                quantity=quantity
            ) #Creo un objeto con los datos del formulario que será guardado en la base de datos
            detail.save() #Guardo el objeto en la base de datos
            return redirect('orders:create-detail', id=data['sale'].id) #Redirigo al usuario a crear los detalles de la nota de venta
    else:
        data['form'] = DetailForm()
        #sendMail(request, id=data['sale'].id)
    return render(request, template_name, data)


def updateDetail(request, id):
    template_name = 'update-detail.html'
    data = {}
    detail = Detail.objects.get(pk=id)

    if request.method == 'POST':
        data['form'] = DetailForm(request.POST or None, instance=detail) #Inicializo un formulario con los datos de la instancia detail
        if data['form'].is_valid():
            detail.save() #Actualizo el detalle
            return redirect('orders:create-detail', id=detail.Numero_boleta.id) #Redirigo al usuario a crear los detalles de la nota de venta
    else:
        data['form'] = DetailForm(instance=detail)

    return render(request, template_name, data)


def deleteDetail(request, id):
    template_name = 'delete-detail.html'
    data = {}
    data['detail'] = Detail.objects.get(pk=id) #Busco el detalle por el id que viene como parametro de la funcion
    boleta = data['detail'].Numero_boleta.id #Extraigo el id de la nota de venta del detalle
    if request.method == 'POST':
        data['detail'].delete() #Elimino el detalle de la nota de venta
        return redirect('orders:create-detail', id=boleta)  #Redirigo al usuario a crear mas detalles de la boleta REVISAR!! 

    return render(request, template_name, data)


def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=orders' + \
        str(datetime.datetime.now())+'.csv' #Creo un archivo csv con la fecha de hoy
    writer = csv.writer(response)
    writer.writerow(['ID', 'Cliente', 'Sucursal',
                    'Fecha', 'Producto', 'Cantidad']) #Columnas del CSV
    details = Detail.objects.all() #Query que será ingresada al csv
    for detail in details:
        writer.writerow([detail.Numero_boleta.id, detail.Numero_boleta.date, detail.Numero_boleta.client,
                        detail.Numero_boleta.sucursal, detail.product, detail.quantity]) #Inserto todas las ocurrencias de la query en el CSV
    return response

orders/templates/Orders.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Notas de venta
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5">
    <div class="col-12">
        <h2 class="mb-4"><strong>Notas de venta</strong></h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block body %}
        {% if orders %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Fecha</th>
                <th scope="col">Cliente</th>
                <th scope="col">Sucursal</th>
                <th scope="col">Editar</th>
                <th scope="col">Editar Detalle</th>
              </tr>
            </thead>
            <tbody>
            {% for order in orders %}
              <tr>
                <td>{{order.id}}</td>
                <td>{{order.date}}</td>
                <td>{{order.client}}</td>
                <td>{{order.sucursal}}</td>
                <td><a href="{% url 'orders:update-order' order.id %}"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a></td>
                <td><a href="{% url 'orders:list-detail' order.id %}"><button type="button" class="btn btn-danger"><i class="fas fa-edit"></i></i></button></a></td>
              </tr>
            {% endfor %}
            </tbody>  
          </table>
        {% endif %}
    </div>
</div>
{% endblock %}

orders/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'orders/style.css' %}" type="text/css">
  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="{% static 'orders/main.js' %}"></script>
  <!-- Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" ></script>
  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <!-- Select2 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.css" />
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/686111fdd6.js" crossorigin="anonymous"></script>
  <title>{% block head %}{% endblock %}</title>
</head>

<body>
  {% if request.user.is_authenticated %}
  <div class="container-{breakpoint}">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style="padding-left: 30px;">
      <a class="navbar-brand" href="{% url 'orders:home' %}">Notas de Venta</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'orders:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <!--<li class="nav-item">
            <a class="nav-link" href="{% url 'auth:profile' %}">Profile</a>
          </li>-->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
          </li>
          <!-- Menu desplegable -->
          <!--           
            <li class="nav-item mr-auto">
              <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> 
          -->
          <!-- Menu desplegable -->
        </ul>
      </div>
    </nav>
  </div>
  {% else %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-left: 30px;">
    <a class="navbar-brand" href="#">Notas de venta</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'orders:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
        </li>
      </ul>
    </div>
  </nav>
  {% endif %}
  <div class="container h-100">
    {% block body %}

    {% endblock %}
  </div>
</body>
</html>
{% block footer %}

{% endblock %}

orders/templates/checkout.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Orden Finalizada
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5">
    <div class="col-12">
        <p>Orden Finalizada</p>
    </div>
</div>

{% endblock %}
{% block body %}
<h1>Orden Finalizada</h1>
{% endblock %}
{% block footer %}
<script>
    setTimeout(function () {
        window.location.href = "{% url 'orders:home' %}";
    }, 3000);
</script>
{% endblock %}

orders/templates/create-detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
Crear nota de venta
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5">
    <div class="col-12">
        <h2 class="mb-4"><strong>Agregar boleta</strong></h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block body %}
        <p style="margin-top: 20px;">Estás realizando una nota de venta para {{sale.client}} en la sucursal {{sale.sucursal}}</p>
        {% if details %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Editar</th>
                <th scope="col">Eliminar</th>
              </tr>
            </thead>
            <tbody>
            {% for detail in details %}
              <tr>
                <td>{{detail.product}}</td>
                <td>{{detail.quantity}}</td>
                <td><a href="{% url 'orders:update-detail' detail.id %}">Editar</a></td>
                <td><a href="{% url 'orders:delete-detail' detail.id %}">Eliminar</a></td>
              </tr>
            {% endfor %}
            </tbody>  
          </table>
        {% endif %}
        <!--Formulario-->
        {% bootstrap_messages %}
        <form action="{% url 'orders:create-detail' sale.id%}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <div class="mb-3 w-60 buttonLoginForm">
              <button class="btn btn-lg btn-block btn-dark form-control mt-3" type="submit">Agregar Detalle</button>
            </div>
            {% endbuttons %}
          </form>
        {% if sale %}
        <div class="mb-3 w-60 buttonLoginForm">
<<<<<<< Updated upstream
          <a class="btn btn-lg btn-block btn-dark form-control mt-3" href="{% url 'orders:send-email' sale.id %}">Finalizar Nota de venta</a>
=======
          <a class="btn btn-lg btn-block btn-dark form-control mt-3" href="{% url 'orders:send-email' sale.id %}">Enviar orden de venta</a>
>>>>>>> Stashed changes
        </div>  
        {% else %}
        <p>nollega</p>
        {% endif %}
        <!--<form action="{% url 'orders:send-email' sale.id %}" method='GET'>
          <div class="mb-3 w-60 buttonLoginForm">
            <button class="btn btn-lg btn-block btn-dark form-control mt-3" type="">Finalizar Orden</button>
          </div>
        </form>   -->    
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}
{% block footer %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script>
  $(document).ready(function () {
      $('#id_product').select2({
          ajax: {
              url: "{% url 'orders:create-detail' sale.pk %}",
              dataType: 'json',
              processResults: function (data) {
                  return {
                      results: $.map(data, function (item) {
                          return {id: item.id, text: item.name};
                      })
                  };
              }
          },
          minimumInputLength: 1
      });
  });
</script>
{% endblock %}

orders/templates/create-orden.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Crear nota de venta
{% endblock %}
{% block content_head %}
<!--Titulo-->
<div class="row round-borderform mt-5">
    <div class="col-12">
        <h2 class="mb-4"><strong>Agregar nota de venta</strong></h2>
        <!--Fin titulo-->
        {% endblock %}
        {% block body %}
        <!--Formulario-->
        {% bootstrap_messages %}
        <form action="{% url 'orders:create'%}" method="POST" id="orderForm" data-cities-url="{% url 'orders:ajax_load_cities' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <div class="mb-3 w-60 buttonLoginForm">
                <button class="btn btn-lg btn-block btn-dark form-control mt-3" type="submit">Crear boleta</button>
            </div>
            {% endbuttons %}
        </form>
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}
{% block footer %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script>
  $(document).ready(function () 
  {
      $('#id_client').select2({
          ajax: {
              url: "{% url 'orders:create'%}",
              dataType: 'json',
              processResults: function (data) {
                  return {
                      results: $.map(data, function (item) {
                          return {id: item.id, text: item.name};
                      })
                  };
              }
          },
          minimumInputLength: 1,
          formatInputTooShort: "Please add more text",
      });
  });
</script>
<script>
    $("#id_client").change(function () {
        const url = $("#orderForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const clientId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'client_id': clientId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);
                //$("#id_sucursal").html(data);  // replace the contents of the city input with the data that came from the server


                let html_data = '<option value="">---------</option>';
                data.forEach(function (sucursal) {
                    html_data += `<option value="${sucursal.id}">${sucursal.name}</option>`
                });
                console.log(html_data);
                $("#id_sucursal").html(html_data);

            }
        });

    });
</script>
{% endblock %}
<!--{% bootstrap_form detailform %}-->

orders/templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block head %}
Home
{% endblock %}
{% block body %}
<div class="row h-100">
    <div class="col-12 centerButton">
        <div class="d-grid gap-2">
            <a class="btn btn-dark" href="{% url 'orders:create' %}" role="button">Nueva nota de venta</a>
            <a class="btn btn-dark" href="{% url 'orders:list-orders' %}" role="button">Editar nota de venta</a>
            <a class="btn btn-dark" href="{% url 'orders:export-csv' %}" role="button">Exportar Csv</a>
            <!--<a class="btn btn-dark" href="{% url 'orders:export-pdf' %}" role="button">Exportar Pdf</a>-->
          </div>
    </div>
</div>

{% endblock %}

orders/templates/sucursal-dropdown.html
<option value="">---------</option>
{% for sucursal in sucursales %}
<option value="{{ sucursal.pk }}">{{ sucursal.name }}</option>
{% endfor %}