auth_login/urls.py
from django.urls import path, include
from auth_login import views
from django.contrib.auth import views as auth_views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    #path('profile/purchases/<int:id>', views.purchases, name='purchases'),
    path('profile/edit', views.editProfile, name='edit'),
    path('profile/change_password', views.change_password, name='change_password'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('auth/', include('auth_login.urls', namespace='auth')),
    #Me trae las funciones de reseteo de contraseña que provee Django
    path('accounts/', include('django.contrib.auth.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth_login/models.py
from django.db import models

# Create your models here.

auth_login/forms.py
from django import forms
from auth_login import views
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='email', required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'           
        ]
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = (self.cleaned_data["first_name"])
        user.last_name = (self.cleaned_data["last_name"])
        user.email = (self.cleaned_data["email"])

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        del self.fields['password']

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

auth_login/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from auth_login.forms import RegistrationForm, EditProfileForm
from django.db import IntegrityError
from datetime import datetime
from orders.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

def register(request):
    template_name = 'register.html'
    #data['form'] = RegistrationForm(request.POST or None)

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            auth.logout(request)
            #auth.login(request, user)
    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request, template_name, args)
    
    return redirect('auth:login') 

def login(request):
    template_name = 'login.html'
    data = {}

    auth.logout(request)
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(
            username=username,
            password=password
        )

        if user is not None:
            ## Usuario autenticado
            if user.is_active:
                #Usuario valido
                auth.login(request, user)
                return redirect('orders:home')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Error user not active.'
                )
                return redirect('auth:login')
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Usuario o Contraseña incorrectos.'
            )
            return redirect('auth:login')
    else:
        return render(request, template_name, data)

def logout(request):
    if request.user.is_authenticated:
        auth.logout(request)
        return redirect('accounts:home')
    else:
        print('no logeado')
        return redirect('accounts:home')


def profile(request):
    template_name = 'profile.html'
    
    data = {'user': UserProfile.objects.get(user=request.user.id)}
    return render(request, template_name, data)



def editProfile(request):
    data = {}
    template_name = 'edit_profile.html'

    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('auth:profile')
    else:
        form = EditProfileForm(instance=request.user)
        data = {'form': form}
        return render(request, template_name, data) 

    return render(request, template_name, data)

def change_password(request):
    data = {}
    template_name = 'change_password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('auth:profile')
        else:
            return redirect('auth:change_password')
    else:
        form = PasswordChangeForm(user=request.user)
        data = {'form': form}
        return render(request, template_name, data)

auth_login/templates/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body %}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5 h-100">
    <div class="col-md-6 mx-auto my-auto">
        <h2>Cambiar Contraseña</h2>
        <!--Fin titulo-->
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Cambiar contraseña
            </button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock %}

auth_login/templates/edit_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body%}
<!--Titulo-->
<div class="row round-borderform mt-5 mb-5">
    <div class="col">
        <h2>Editar perfil</h2>
        <!--Fin titulo-->
        {% bootstrap_messages %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Confirmar cambios
            </button>
            {% endbuttons %}
        </form>

    </div>
</div>
{% endblock %}

auth_login/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block head %}
Login
{% endblock %}
{% block body %}
<div class="row h-100">
    <div class="col-12 mx-auto my-auto">
        <form class="form-signin" method="POST">
            {% csrf_token %}
            <div class="text-center mb-4">
                <h1>Ingreso de usuarios</h1>
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="w-100 mb-3 loginForm">
                <label class="mb-2" for="username">Nombre de usuario</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="Nombre de usuario" required
                    autofocus>
            </div>

            <div class="w-100 mb-3 loginForm">
                <label class="mb-2" for="password">Contraseña</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña"
                    required>
            </div>
            <div class="mb-3 w-60 buttonLoginForm">
                <button class="btn btn-lg btn-block btn-dark form-control mt-3" type="submit">Entrar</button>
            </div>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2019</p>
            <!--<div class="checkbox mb-3 w-50 mx-auto mb-1">
                <label>
                    <input type="checkbox" value="remember-me"> Recuérdame
                </label>
                
            </div>-->
            <!--<span><a href="{% url 'auth:register' %}">Registrarse</a></span>-->
        </form>
    </div>
</div>
{% endblock %}

<!--<div class="col-12 col-sm-6 mt-5">
        <div class="jumbotron">
            <h1 class="mb-5">CREAR UNA CUENTA</h1>
            <p class="lead">Crear una cuenta es fácil. Ingresa tu dirección de correo electrónico, llena el formulario
                de la página siguiente y disfruta de tus beneficios</p>
            <hr class="">
            <a class="btn btn-primary btn-lg mt-3" href="{% url 'auth:register' %}" role="button">Registrarse</a>
        </div>
    </div>-->

auth_login/templates/password_reset_form.html
{% extends 'base.html' %}

{% block head %}Forgot Your Password?{% endblock %}

{% block body %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

auth_login/templates/profile.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Información de tu Perfil
{% endblock %}
{% block body %}
<!--Formulario-->

<div class="row h-100">
  <div class="col-md-6 mx-auto my-auto">
    <div class="card mb-5 align-center">
      <div class="card-body">
        <h3 class="card-title"><strong>Tus datos</strong></h3>
        <h6>Nombre</h6>
        <p class="card-text">{{user.user.first_name}} {{user.user.last_name}}</p>
        <h6>Email</h6>
        <p class="card-text">{{user.user.email}}</p>
        <h6>Calle</h6>
        <p class="card-text">{{user.address}}</p>
        <h6>Ciudad</h6>
        <p class="card-text">{{user.city}}</p>
        <h6>Telefono</h6>
        <p class="card-text">{{user.phone}}</p>
        <a href="{% url 'auth:edit' %}" class="btn btn-primary mr-2"><i class="far fa-edit text-center"></i></a>
        <a href="{% url 'auth:change_password' %}" class="btn btn-primary"><i class="fas fa-key"></i></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}


<!-- <div class="row round-borderform">
     <div class="col">
        <h2>Perfil</h2>  -->

auth_login/templates/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block head %}
Crear usuario
{% endblock %}
{% block body %}
<!--Titulo-->
<div class="row round-borderform">
    <div class="col-md-12">
        <h2>Registrarse</h2>
        <!--Fin titulo-->
        
        <!--Formulario-->
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Crear usuario!
            </button>
            {% endbuttons %}
        </form>
        <!--Fin formulario-->
    </div>
</div>
{% endblock %}